# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64742add1b7f6a3525eb1f845de2491b19a2bbf6749cc34385cb79b313ae78bbd4bcb9b1508948c4af593172b35cd278ba90a11a1c8db1d6f6d0bdc30d5f97c1

test:
  secret_key_base: 98251099e806b8ba990680748576c402fdb027d322405074c0e29bcc1848f99b9665616ac5a338c847aad5ad4ae0b373f92a116395eab7290a7c96bd2815e6ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
